# Site settings
title: Exaforge
description: Cloud, DevOps, Evangelism
email: matt@cowger.us
url: "http://mcowger.github.io" # the base hostname & protocol for your site
#favicon
favicon: /favicon.png


#twitter
twitter_username: mcowger
github_username:  mcowger

#linkedin
linkedin_username: mcowger

repository: mcowger/mcowger.github.io

#google analytics
#google_analytics_id : UA-53386152-2
#gplus
#gplus_username: 101893920934936418705

#fb_username
#fb_username: pranav.tayberrycreative

#permalink /blog/2014/11/11/this-is-a-sample-post
permalink: /:title/
# Build settings
markdown: kramdown

#Disqus configuration
#disqus_short_name: maangalabscom
#disqus_show_comment_count: true

#Can be used for multiple author blogs ! Add name to post For more visit the sample
